<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MqttSubscriberWorkerService-a3419566-6cf5-4967-a4c5-90236bd238b0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="MQTTnet" Version="5.1.0.1559" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MqttPoc.Shared\MqttPoc.Shared\MqttPoc.Shared.csproj" />
    <ProjectReference Include="..\..\MqttPOC\MqttPoc.csproj" />
  </ItemGroup>
</Project>
